"""Create model

Revision ID: 39a23b6b699d
Revises: 
Create Date: 2025-08-22 21:16:17.925146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a23b6b699d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aaskUsers',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('date_registr', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_aaskUsers_chat_id'), 'aaskUsers', ['chat_id'], unique=False)
    op.create_table('groups',
    sa.Column('groups', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('groups')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.drop_index(op.f('ix_aaskUsers_chat_id'), table_name='aaskUsers')
    op.drop_table('aaskUsers')
    # ### end Alembic commands ###
