"""Новые модели address, college

Revision ID: 520c638b669e
Revises: f965d5d85d2e
Create Date: 2026-02-05 21:37:44.012068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "520c638b669e"
down_revision: Union[str, None] = "f965d5d85d2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("sid"),
        sa.UniqueConstraint("sid"),
    )
    op.create_index(op.f("ix_address_name"), "address", ["name"], unique=False)
    op.create_table(
        "college",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("sid"),
        sa.UniqueConstraint("sid"),
    )
    op.create_index(op.f("ix_college_name"), "college", ["name"], unique=False)
    op.drop_index(op.f("ix_groups_is_active"), table_name="group")
    op.drop_index(op.f("ix_groups_name"), table_name="group")
    op.create_index(op.f("ix_group_is_active"), "group", ["is_active"], unique=False)
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=False)
    op.alter_column(
        "sender_logs",
        "created_at",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "sender_logs", ["sid"])
    op.drop_index(op.f("ix_aaskUsers_chat_id"), table_name="user")
    op.drop_index(op.f("ix_aaskUsers_is_active"), table_name="user")
    op.create_index(op.f("ix_user_chat_id"), "user", ["chat_id"], unique=True)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_chat_id"), table_name="user")
    op.create_index(op.f("ix_aaskUsers_is_active"), "user", ["is_active"], unique=False)
    op.create_index(op.f("ix_aaskUsers_chat_id"), "user", ["chat_id"], unique=True)
    op.drop_constraint(None, "sender_logs", type_="unique")
    op.alter_column(
        "sender_logs",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_group_name"), table_name="group")
    op.drop_index(op.f("ix_group_is_active"), table_name="group")
    op.create_index(op.f("ix_groups_name"), "group", ["name"], unique=False)
    op.create_index(op.f("ix_groups_is_active"), "group", ["is_active"], unique=False)
    op.drop_index(op.f("ix_college_name"), table_name="college")
    op.drop_table("college")
    op.drop_index(op.f("ix_address_name"), table_name="address")
    op.drop_table("address")
    # ### end Alembic commands ###
