"""Create AASKuser model

Revision ID: 964629983061
Revises: 
Create Date: 2025-08-14 19:55:35.138533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964629983061'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aaskUsers',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('date_registr', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('group_name'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_aaskUsers_chat_id'), 'aaskUsers', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aaskUsers_chat_id'), table_name='aaskUsers')
    op.drop_table('aaskUsers')
    # ### end Alembic commands ###
