"""message

Revision ID: 9f99a533daf4
Revises: d37c8bc1df4f
Create Date: 2025-08-31 17:41:10.136849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f99a533daf4"
down_revision: Union[str, None] = "d37c8bc1df4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "aaskUsers",
        "chat_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_aaskUsers_chat_id"), table_name="aaskUsers")
    op.create_index(op.f("ix_aaskUsers_chat_id"), "aaskUsers", ["chat_id"], unique=True)
    op.create_unique_constraint(None, "groups", ["sid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="unique")
    op.drop_index(op.f("ix_aaskUsers_chat_id"), table_name="aaskUsers")
    op.create_index(
        op.f("ix_aaskUsers_chat_id"), "aaskUsers", ["chat_id"], unique=False
    )
    op.alter_column(
        "aaskUsers",
        "chat_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
