"""create sender_logs table

Revision ID: c605822246cf
Revises: 402e64d0126e
Create Date: 2026-01-26 18:06:15.736134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c605822246cf'
down_revision: Union[str, None] = '402e64d0126e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sender_logs',
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sender_logs')
    # ### end Alembic commands ###