"""message

Revision ID: d37c8bc1df4f
Revises:
Create Date: 2025-08-31 15:43:07.068810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d37c8bc1df4f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("sid"),
        sa.UniqueConstraint("sid"),
    )
    op.create_index(op.f("ix_groups_is_active"), "groups", ["is_active"], unique=False)
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
    op.create_table(
        "aaskUsers",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("group_sid", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_sid"], ["groups.sid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chat_id", "sid"),
        sa.UniqueConstraint("sid"),
    )
    op.create_index(
        op.f("ix_aaskUsers_chat_id"), "aaskUsers", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_aaskUsers_is_active"), "aaskUsers", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_aaskUsers_is_active"), table_name="aaskUsers")
    op.drop_index(op.f("ix_aaskUsers_chat_id"), table_name="aaskUsers")
    op.drop_table("aaskUsers")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_index(op.f("ix_groups_is_active"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
